---
- import_playbook: 'playbooks/configure_git.yml'

- import_playbook: 'playbooks/configure_terminal.yml'

- import_playbook: 'playbooks/configure_user.yml'

- import_playbook: 'playbooks/configure_tmux.yml'

- import_playbook: 'playbooks/configure_docker.yml'

- import_playbook: 'playbooks/configure_k8s_tools.yml'

- import_playbook: 'playbooks/configure_visual_studio_code.yml'