---
- import_playbook: 'playbooks/configure_git.yml'

- import_playbook: 'playbooks/configure_terminal.yml'

- import_playbook: 'playbooks/configure_user.yml'

- import_playbook: 'playbooks/configure_tmux.yml'
