galaxy_info:
  author: Aleksander Gondek
  description: Ansible role to install and configure docker on Fedora.

  license: MIT

  min_ansible_version: 2.4

  platforms:
   - name: Fedora
     versions:
     - all

  galaxy_tags: ['docker', 'docker-compose', 'fedora']

dependencies: []
