---
ansible_user: "{{ vault_os_user_name }}"
ansible_python_interpreter: /usr/bin/python3

user_configration:
  uid: 1000
  name: "{{ vault_os_user_name }}"
  comment: "{{ vault_os_user_comment }}"
  group_name: "{{ vault_os_user_name }}"
  group_id: 1000

git_configuration:
  'user.name': "{{ vault_git_user_name }}"
  'user.email': "{{ vault_git_user_email }}"
  'user.signingkey': "{{ vault_git_user_signingkey }}"
  'gpg.program': gpg2
  'commit.gpgsign': true

oh_my_zsh_configuration:
  theme: "agnoster"
  plugins:
    - bundler
    - dirhistory
    - dnf
    - docker
    - gem
    - git
    - pip
    - tmux
    - vagrant
    - yarn
