---
ansible_fedora_docker_purge: true

ansible_fedora_docker_yum_repos:
  - name: "docker-ce-stable"
    filename: docker-ce-stable
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
    enabled: 1
    gpgcheck: 1
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

  - name: "docker-ce-edge"
    filename: docker-ce-edge
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/edge"
    enabled: 0
    gpgcheck: 1
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

  - name: "docker-ce-test"
    filename: docker-ce-test
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/test"
    enabled: 0
    gpgcheck: 1
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

  - name: "docker-ce-nightly"
    filename: docker-ce-nightly
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/nightly"
    enabled: 0
    gpgcheck: 1
    gpgkey: "https://download.docker.com/linux/fedora/gpg"
