---
ansible_fedora_docker_purge: true

ansible_fedora_docker_yum_repos: []
ansible_fedora_docker_default_yum_repos:
  - name: "docker-ce-stable"
    filename: docker-ce-stable
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/stable"
    enabled: true
    gpgcheck: false
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

  - name: "docker-ce-edge"
    filename: docker-ce-edge
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/edge"
    enabled: false
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

  - name: "docker-ce-test"
    filename: docker-ce-test
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/test"
    enabled: false
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

  - name: "docker-ce-nightly"
    filename: docker-ce-nightly
    baseurl: "https://download.docker.com/linux/fedora/$releasever/$basearch/nightly"
    enabled: false
    gpgcheck: true
    gpgkey: "https://download.docker.com/linux/fedora/gpg"

ansible_fedora_docker_data_root: "/var/lib/docker"
ansible_fedora_docker_log_driver: "json-file"
ansible_fedora_docker_log_opts:
    "max-size": '1g'
    "max-file": '1'
ansible_fedora_docker_storage_driver: "overlay2"

ansible_fedora_docker_gid: 1001
ansible_fedora_docker_users: []

ansible_fedora_docker_compose_install: true
ansible_fedora_docker_compose_version: "1.23.1"
ansible_fedora_docker_compose_checksum: "sha256:c176543737b8aea762022245f0f4d58781d3cb1b072bc14f3f8e5bb96f90f1a2"
ansible_fedora_docker_compose_install_path: "/usr/bin/docker-compose"

ansible_fedora_docker_cron_jobs: []
ansible_fedora_docker_default_cron_jobs:
  - name: "Docker system prune - once a day"
    file_name: "docker_system_prune"
    job: 'docker system prune -af &> /dev/null'
    schedule: ["0", "0", "*", "*", "*"]
    user: "{{ (ansible_fedora_docker_users | first) | default('root') }}"
