---
- name: "Prepare a working git environment"
  hosts: all
  tasks:
    - name: "Ensure git, gitk and git-crypt are installed"
      become: true
      dnf:
        name: 
          - git
          - gitk
          - git-crypt
        state: present

    - name: "Configure git with appropriate information"
      git_config:
        name: "{{ item.key }}"
        scope: global
        value: "{{ item.value }}"
      with_dict: "{{ git_configuration }}"
