---
- name: "Configure and customize terminal to match my expectations"
  hosts: all
  tasks:
    - name: "Ensure oh-my-zsh pre-requirements are installed"
      become: true
      dnf:
        name:
          - curl
          - git
          - zsh
          - libselinux-python
          - powerline-fonts
        state: present

    - name: Download oh-my-zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/install-oh-my-zsh.sh
        mode: "u+rwx"

    - name: "Run oh-my-zsh installation"
      script: /tmp/install-oh-my-zsh.sh

    - name: "Set oh-my-zsh theme to '{{ oh_my_zsh_configuration.theme }}'"
      lineinfile:
        path: "~/.zshrc"
        regexp: "^ZSH_THEME="
        line: "ZSH_THEME={{ oh_my_zsh_configuration.theme }}"

    - name: "Enable oh-my-zsh plugins"
      replace:
        path: "~/.zshrc"
        regexp: 'plugins=\(\n  git\n\)'
        replace: "plugins=(\n {{ oh_my_zsh_configuration.plugins | join('\n ') }} \n)"

    - name: "Auto start tmux while logging in"
      lineinfile:
        path: "~/.zshrc"
        line: "ZSH_TMUX_AUTOSTART=true"
        insertbefore: BOF

    - name: "Get information about pip3 user site install location"
      command: "python3 -m site --user-base"
      register: pip3_user_bin_info

    - name: "Ensure .profile file exists"
      file:
        path: ~/.profile
        state: touch

    - name: "Ensure pip3 --user bin location is added to $PATH for .profile"
      lineinfile:
        path: "~/.profile"
        regexp: "^export PATH="
        line: "export PATH=\"$PATH:{{ pip3_user_bin_info.stdout }}/bin\""

    - name: "Ensure .zprofile file exists"
      file:
        path: ~/.zprofile
        state: touch

    - name: "Ensure pip3 --user bin location is added to $PATH for .zprofile"
      lineinfile:
        path: "~/.zprofile"
        regexp: "^export PATH="
        line: "export PATH=\"$PATH:{{ pip3_user_bin_info.stdout }}/bin\""
