---
- name: "Configure and customize terminal to match my expectations"
  hosts: all
  tasks:
    - name: "Ensure oh-my-zsh pre-requirements are installed"
      become: true
      dnf:
        name:
          - curl
          - git
          - zsh
          - libselinux-python
          - powerline-fonts
        state: present

    - name: Download oh-my-zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/install-oh-my-zsh.sh
        mode: "u+rwx"

    - name: "Run oh-my-zsh installation"
      script: /tmp/install-oh-my-zsh.sh

    - name: "Set oh-my-zsh theme to '{{ oh_my_zsh_configuration.theme }}'"
      lineinfile:
        path: "~/.zshrc"
        regexp: "^ZSH_THEME="
        line: "ZSH_THEME={{ oh_my_zsh_configuration.theme }}"

    - name: "Enable plugins"
      replace:
        path: "~/.zshrc"
        regexp: 'plugins=\(\n  git\n\)'
        replace: "plugins=(\n {{ oh_my_zsh_configuration.plugins | join('\n') }} \n)"
