---
- name: "Configure and customize terminal to match my expectations"
  hosts: all
  tasks:
    - name: "Ensure oh-my-zsh pre-requirements are installed"
      become: true
      dnf:
        name:
          - curl
          - git
          - zsh
          - libselinux-python
          - powerline-fonts
        state: present

    - name: Download oh-my-zsh installation script
      get_url:
        url: https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
        dest: /tmp/install-oh-my-zsh.sh
        mode: "u+rwx"

    - name: "Run oh-my-zsh installation"
      script: /tmp/install-oh-my-zsh.sh

    - name: "Set oh-my-zsh theme to '{{ oh_my_zsh_configuration.theme }}'"
      lineinfile:
        path: "~/.zshrc"
        regexp: "^ZSH_THEME="
        line: "ZSH_THEME={{ oh_my_zsh_configuration.theme }}"

    - name: "Enable oh-my-zsh plugins"
      replace:
        path: "~/.zshrc"
        regexp: 'plugins=\(\n  git\n\)'
        replace: "plugins=(\n {{ oh_my_zsh_configuration.plugins | join('\n ') }} \n)"

    - name: "Ensure tmux et. al. pre-requirements are installed"
      become: true
      dnf:
        name:
          - python3-pip
          - tmux
        state: present

    - name: "Ensure powerline-status is installed"
      pip:
        name: powerline-status
        executable: pip3
        state: present

    - name: "Get information about powerline installation"
      command: "pip3 show powerline-status"
      register: powerline_pip_info

    - name: "Retrieve powerline installation dir"
      set_fact:
        powerline_dir: "{{ powerline_pip_info.stdout_lines[7].split(':')[1] }}/powerline"
